### ISSUE TITLE
Unhandled device/BRAVIA KDL-46X4500

### ISSUE THREAD

**Issue by jkiddo** [KHerron/SonyAPILib#13]
Hi ... 

I'm encountering a bug when using the Console Example Program. Is it because of a unsupported device?

See the following:

...

Enter the Device # to Test
26

http://192.168.1.4:52323/mr.xml: Building Device....
BRAVIA KDL-46X4500     : Checking Device Status....

Get Status returned: Error
---------------------------------

BRAVIA KDL-46X4500     : Performing Registration....
Before continuing, you may need to set the device to Registration Mode,
Confirm Registration or enter the Registration PIN code.
Go to the device and perfrom any step, and be ready before hitting enter below!
=====================================
Hit any key to continue

Registration returned: False
---------------------------------

There was an error
---------------------------------

BRAVIA KDL-46X4500     : Retrieving Remote Command List
ERROR Retrieving Command List
---------------------------------

BRAVIA KDL-46X4500     : Retrieving Command Value for: VolumeUp

Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00010] in <63992662b765477a898ef49cdcc99ee2>:0 
  at SonyAPILib.APILibrary+SonyDevice.GetCommandString (System.String CmdName) [0x00036] in <f5c8cdd83b414251b6266891cbc5dcf5>:0 
  at ConsoleExample.Program.Main (System.String[] args) [0x004cf] in <976d2998bd1746d8ac37016f02463cc0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00010] in <63992662b765477a898ef49cdcc99ee2>:0 
  at SonyAPILib.APILibrary+SonyDevice.GetCommandString (System.String CmdName) [0x00036] in <f5c8cdd83b414251b6266891cbc5dcf5>:0 
  at ConsoleExample.Program.Main (System.String[] args) [0x004cf] in <976d2998bd1746d8ac37016f02463cc0>:0

**Comment by jkiddo** [comment]
[mr.xml.txt](https://github.com/KHerron/SonyAPILib/files/751557/mr.xml.txt)

**Comment by KHerron** [comment]
I do not see your model in the following compatibility list.

LCD TV BRAVIA:

XBR-xxX95xB series  XBR-xxX90xB series  XBR-xxX90xA series  XBR-xxX85xB series  XBR-xxX85xA series  XBR-xxHX95 series  XBR-xxHX92 series KD-xxX95xxB series  KD-xxX90xxB series  KD-xxX900xA series  KD-xxX900x series  KD-xxX85xxB series KD-xxX850xA series  KD-xxX80xxB series KDL-xxW95xB series  KDL-xxW95xA series  KDL-xxW92xA series  KDL-xxW90xB series  KDL-xxW90xA series  KDL-xxW8xxB series  KDL-xxW85xA series KDL-xxW80xA series  KDL-xxW7xxB series  KDL-xxW70xA series  KDL-xxW6xxB series  KDL-xxW67xA series  KDL-xxW65xA series  KDL-xxW60xA series KDL-xxW5xxA series  KDL-xxS99xA series  KDL-xxNX72 series  KDL-xxNX65 series  KDL-xxHX95 series  KDL-xxHX92 series  KDL-xxHX85 series KDL-xxHX82 series  KDL-xHX75 series  KDL-xxHX72 series  KDL-xxEX75 series  KDL-xxEX72 series  KDL-xxEX65 series  KDL-xxEX62 series KDL-xxEX55 series  KDL-xxEX54 series  KDL-xxEX52 series  KDL-xxEX42 series  KDL-xxEX32 series  KDL-xxCX52 series  KDL-xxCX40 series

How Old is your TV?
Does the Sony TV Sideview phone app work with your TV?

**Comment by jkiddo** [comment]
Its from spring 2009 and the app is not supported

**Comment by KHerron** [comment]
Unfortunately,

 

This means that my API is not compatible either……

 

Sorry

 

Kirk

**Comment by KHerron** [comment]
Closing this issue as it was determined not to be code related.
