### ISSUE TITLE
Question - power IRCC not working on KDL-32CX523, other commands are ok 

### ISSUE THREAD

**Issue by beardedfool** [KHerron/SonyAPILib#19]
Hi,

Please close if this is unwanted but thought you may be able to help. Pretty please?

I've an old KDL-32CX523 and I can use most commands over IRCC commands, except for Power Off
Well, and Power on but I'm pretty sure the WOL doesn't work for that and not sure if IRCC works when in standby (?)

There's a bit more information from the xml here, which would seem to indicate I'm using the correct command.. https://community.openhab.org/t/sony-devices-binding/14052/422

Just wondered if you'd come across anything similar?

Many thanks for even looking at this and hope you'll forgive me asking but have been pulling my hair out and a bit out of my depth on this.

**Comment by KHerron** [comment]
@beardedfool,
From the information you provided, it appears your TV is the same generation as mine. (Uses Mode-2 for registration). This means there is not a WOL function and when you go to standby or Power Off, the NIC gets powered down also. (So no network connection). You can verify this by pinging the device when in these states. You will see you do not get a response. So powering the device to ON, will not work.

Are you using my API, or are you writing your own code?

Here is why I ask, Even though you see those 3 entries in the description file
```
Power OFF=ircc:AAAAAQAAAAEAAAAvAw%3D%3D
Power ON=ircc:AAAAAQAAAAEAAAAuAw%3D%3D
Power=ircc:AAAAAQAAAAEAAAAVAw%3D%3D
```
They do not work. If you look more closely to the Retrieved RemoteCommandList, you will see that there is not a command for "Power On" or "Power Off".
However, there is a "Power" toggle. and it should be sent as: AAAAAQAAAAEAAAAVAw==
You should not encode these, as they are part of the SOAP envelope.

Give this a try, hopefully this will work for you.
I really never used the Power command before. Maybe I'll try when I get a chance this evening.

**Comment by beardedfool** [comment]
Thanks so much for coming back to me.

I think you're right that there's no WOL. 
I thought before that it would ping on standby, but not when the power button on the TV was turned off. 100% that was correct as I've seen that happen. 
Yet testing it now I'm watching it respond to pings when off. Bizarre. Still, it won't respond to WOL packets so that's out.

I'm not using your API, I'm afraid, or not directly, though I may come back to it.  Using that implementation on the open hab. In case it's useful there's a whole list of commands that came back from that.

`acTVila=ircc:AAAAAgAAABoAAAByAw%3D%3D
Advance=ircc:AAAAAgAAAJcAAAB4Aw%3D%3D
Analog=ircc:AAAAAgAAAHcAAAANAw%3D%3D
AppliCast=ircc:AAAAAgAAABoAAABvAw%3D%3D
Audio=ircc:AAAAAQAAAAEAAAAXAw%3D%3D
Blue=ircc:AAAAAgAAAJcAAAAkAw%3D%3D
BS=ircc:AAAAAgAAAJcAAAAsAw%3D%3D
BSCS=ircc:AAAAAgAAAJcAAAAQAw%3D%3D
ChannelDown=ircc:AAAAAQAAAAEAAAARAw%3D%3D
ChannelUp=ircc:AAAAAQAAAAEAAAAQAw%3D%3D
ClosedCaption=ircc:AAAAAgAAAKQAAAAQAw%3D%3D
Confirm=ircc:AAAAAQAAAAEAAABlAw%3D%3D
CS=ircc:AAAAAgAAAJcAAAArAw%3D%3D
Ddata=ircc:AAAAAgAAAJcAAAAVAw%3D%3D
DeleteVideo=ircc:AAAAAgAAAHcAAAAfAw%3D%3D
Digital=ircc:AAAAAgAAAJcAAAAyAw%3D%3D
Display=ircc:AAAAAQAAAAEAAAA6Aw%3D%3D
DOT=ircc:AAAAAgAAAJcAAAAdAw%3D%3D
Down=ircc:AAAAAQAAAAEAAAB1Aw%3D%3D
EasyStartUp=ircc:AAAAAgAAAHcAAABqAw%3D%3D
Eject=ircc:AAAAAgAAAJcAAABIAw%3D%3D
EPG=ircc:AAAAAgAAAKQAAABbAw%3D%3D
Exit=ircc:AAAAAQAAAAEAAABjAw%3D%3D
Forward=ircc:AAAAAgAAAJcAAAAcAw%3D%3D
GGuide=ircc:AAAAAQAAAAEAAAAOAw%3D%3D
Green=ircc:AAAAAgAAAJcAAAAmAw%3D%3D
Home=ircc:AAAAAQAAAAEAAABgAw%3D%3D
iManual=ircc:AAAAAgAAABoAAAB7Aw%3D%3D
Input=ircc:AAAAAQAAAAEAAAAlAw%3D%3D
InternetVideo=ircc:AAAAAgAAABoAAAB5Aw%3D%3D
InternetWidgets=ircc:AAAAAgAAABoAAAB6Aw%3D%3D
Jump=ircc:AAAAAQAAAAEAAAA7Aw%3D%3D
Left=ircc:AAAAAQAAAAEAAAA0Aw%3D%3D
Mode3D=ircc:AAAAAgAAAHcAAABNAw%3D%3D
Mute=ircc:AAAAAQAAAAEAAAAUAw%3D%3D
MuteOff=url:http%3A%2F%2F192.168.21.16%3A80%2Fcers%2Fcommand%2FMuteOff
MuteOn=url:http%3A%2F%2F192.168.21.16%3A80%2Fcers%2Fcommand%2FMuteOn
MyEPG=ircc:AAAAAgAAAHcAAABrAw%3D%3D
Next=ircc:AAAAAgAAAJcAAAA9Aw%3D%3D
Num0=ircc:AAAAAQAAAAEAAAAJAw%3D%3D
Num11=ircc:AAAAAQAAAAEAAAAKAw%3D%3D
Num12=ircc:AAAAAQAAAAEAAAALAw%3D%3D
Num1=ircc:AAAAAQAAAAEAAAAAAw%3D%3D
Num2=ircc:AAAAAQAAAAEAAAABAw%3D%3D
Num3=ircc:AAAAAQAAAAEAAAACAw%3D%3D
Num4=ircc:AAAAAQAAAAEAAAADAw%3D%3D
Num5=ircc:AAAAAQAAAAEAAAAEAw%3D%3D
Num6=ircc:AAAAAQAAAAEAAAAFAw%3D%3D
Num7=ircc:AAAAAQAAAAEAAAAGAw%3D%3D
Num8=ircc:AAAAAQAAAAEAAAAHAw%3D%3D
Num9=ircc:AAAAAQAAAAEAAAAIAw%3D%3D
OneTouchRec=ircc:AAAAAgAAABoAAABiAw%3D%3D
OneTouchRecStop=ircc:AAAAAgAAABoAAABjAw%3D%3D
OneTouchTimeRec=ircc:AAAAAgAAABoAAABkAw%3D%3D
OneTouchView=ircc:AAAAAgAAABoAAABlAw%3D%3D
Options=ircc:AAAAAgAAAJcAAAA2Aw%3D%3D
PAP=ircc:AAAAAgAAAKQAAAB3Aw%3D%3D
Pause=ircc:AAAAAgAAAJcAAAAZAw%3D%3D
Play=ircc:AAAAAgAAAJcAAAAaAw%3D%3D
PopUpMenu=ircc:AAAAAgAAABoAAABhAw%3D%3D
Power OFF=ircc:AAAAAQAAAAEAAAAvAw%3D%3D
Power ON=ircc:AAAAAQAAAAEAAAAuAw%3D%3D
Power=ircc:AAAAAQAAAAEAAAAVAw%3D%3D
Prev=ircc:AAAAAgAAAJcAAAA8Aw%3D%3D
ProgramDescription=ircc:AAAAAgAAAJcAAAAWAw%3D%3D
Rec=ircc:AAAAAgAAAJcAAAAgAw%3D%3D
Red=ircc:AAAAAgAAAJcAAAAlAw%3D%3D
Replay=ircc:AAAAAgAAAJcAAAB5Aw%3D%3D
Return=ircc:AAAAAgAAAJcAAAAjAw%3D%3D
Rewind=ircc:AAAAAgAAAJcAAAAbAw%3D%3D
Right=ircc:AAAAAQAAAAEAAAAzAw%3D%3D
SceneSelect=ircc:AAAAAgAAABoAAAB4Aw%3D%3D
Stop=ircc:AAAAAgAAAJcAAAAYAw%3D%3D
SubTitle=ircc:AAAAAgAAAJcAAAAoAw%3D%3D
SyncMenu=ircc:AAAAAgAAABoAAABYAw%3D%3D
Teletext=ircc:AAAAAQAAAAEAAAA%2FAw%3D%3D
TenKey=ircc:AAAAAgAAAJcAAAAMAw%3D%3D
TopMenu=ircc:AAAAAgAAABoAAABgAw%3D%3D
TrackID=ircc:AAAAAgAAABoAAAB%2BAw%3D%3D
Up=ircc:AAAAAQAAAAEAAAB0Aw%3D%3D
VolumeDown=ircc:AAAAAQAAAAEAAAATAw%3D%3D
VolumeUp=ircc:AAAAAQAAAAEAAAASAw%3D%3D
Wide=ircc:AAAAAgAAAKQAAAA9Aw%3D%3D
WriteChapter=ircc:AAAAAgAAAHcAAABsAw%3D%3D
Yellow=ircc:AAAAAgAAAJcAAAAnAw%3D%3D`

Although some other ones seem to work as well e.g. 
`Hdmi1=AAAAAgAAABoAAABaAw%3D%3D
Hdmi2=AAAAAgAAABoAAABbAw%3D%3D
Hdmi3=AAAAAgAAABoAAABcAw%3D%3D
Hdmi4=AAAAAgAAABoAAABdAw%3D%3D`

Just sadly not the power. I've tried it with %3D and = signs. In that openhab binding the author came back with "(note: don’t replace the %3D with equals in the map file - those are encoded and decoded on purpose)."

For the moment I'm trying to work out LIRC on a rasberry PI and go the IR route to see if that works a bit better but really appreciate you coming back to me.  I'm pretty sure that the TV just ignores those codes as I've tested sending them through this as well, so I don't think it's a problem in his code. 

`https://github.com/breunigs/bravia-auth-and-remote`

Just seems so wrong it doesn't work when all the other commands do and the TV itself returns those codes to use. That's sony I guess.

Interesting that you're not using the power,  I'd assume that's one of the more useful ones. Do you use some other method (CEC?) toggle power, or just use the remote?   If you do get a chance to test it at some point I'd appreciate it, I've got that nagging feeling of unfinished business ;)

**Comment by beardedfool** [comment]
PS. I'm happy for you to close this if you want, I'll leave it open in case you do get a chance to test it, but huge thanks for spending the time looking at it. Much appreciated

**Comment by KHerron** [comment]
OK, I have tested this with my Bravia and you are correct. NONE of the power commands.

I do get a response:
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <s:Body> <u:X_SendIRCCResponse xmlns:u="urn:schemas-sony-com:service:IRCC:1"> </u:X_SendIRCCResponse> </s:Body> </s:Envelope>`
but nothing happens. This must be a Sony thing for our model.

I'm going to close this issue for now, as it is not an issue with my API.
Thanks for your interest. Let me know if I can be of any other help.
