### ISSUE TITLE
callbacks possible?

### ISSUE THREAD

**Issue by krisrok** [KHerron/SonyAPILib#7]
have you encountered any way for adding callbacks[/event handlers/hooks/whatever you may call it] so you can react to certain events? i'm currently looking into this and saw you have quite some expertise in this area :)

**Comment by KHerron** [comment]
If you are talking about the device being able to notify the API that an event has occurred at the device such as Volume change or Channel Change, then NO. During my Wireshark captures with either of my Gen 1 or Gen 2 devices, the device do not send out any information when there is a change at the device.

However, there are some UPnP State-Variables that do change as you make changes at the device. So YES, we could possibly set up a Listener that watches these state-varables and then notifies the API when there is a change.

Not sure what generation of device you have, but there is a HUGE different with Generation 3 devices. So it could take some research, testing and Trial and errors to figure it all out.

Once I am able to release 5.1, I plan to start advancing with more abilities and controls, but wanted to get the CORE of the API working correctly before I moved forward.

**Comment by krisrok** [comment]
thanks for the labelling. could i have done that myself?

great to hear about that there might be hope. do you know what kind of status info is available? 

i have a bravia model, don't know which exactly, but i'm pretty sure i read 3rd gen when running your console app.

**Comment by KHerron** [comment]
Download this project http://managedupnp.codeplex.com/ 
The run the ManagedUPnPTest.exe in the bin folder.

It should find your TV and show you all the supported functions including the state variables.
My API already uses this library, and I plan to start advancing in to it deeper and providing my API more capabilities and options.

**Comment by KHerron** [comment]
Created a Google Group Forum for this project. Here is the address if you want to join. 
https://groups.google.com/d/forum/sony-api-library 
Thx.

**Comment by KHerron** [comment]
New version of API is out for testing. Still no event handlers for the State variables, but there is a whole lot of new things. Services have been put directly in to the API and state variables are now getting populated. After some more testing, I will start trying to add the events!

**Comment by KHerron** [comment]
Eventing is going in on version 5.3.
However, I am not closing this issue until further testing has been completed.
Please see the Wiki for Changes Information, Event server information and the Eventing console example application.

Also, please report any issues, bugs or concerns here!

**Comment by KHerron** [comment]
Eventing or Callbacks have been implemented since 5.3.
Closing this issue as to no reports.
